import './img/avatar.jpg';
import './img/favicon.ico';
import './img/main-slider/01.jpg';
import './img/main-slider/02.jpg';
import './img/main-slider/03.jpg';
import './img/advantages/01.svg';
import './img/advantages/02.svg';
import './img/advantages/03.svg';
import './img/advantages/04.svg';
import './img/products/prod01.jpg';
import './img/products/prod02.jpg';
import './img/products/prod03.jpg';
import './img/products/prod04.jpg';
import './img/products/prod05.jpg';
import './img/products/prod06.jpg';
import './img/products/prod07.jpg';
import './img/products/prod08.jpg';
import './img/rooms/room01.jpg';
import './img/rooms/room02.jpg';
import './img/rooms/room03.jpg';

import './js/functions.js';
import './js/forms.js';
import './js/sliders.js';
import './js/dynamic_adapt.js';
import './js/script.js';
import './json/products.json';

import './styles/main.scss';